database:
  type: dynamodb
  flowTableName: 'k8s-tams-test'
  serviceTableName: 'k8s-tams-test-service'
  sourceTableName: 'k8s-tams-test-source'
  mediaObjectTableName: 'k8s-tams-test-media-object'
  flowDeleteRequestsTableName: 'k8s-tams-test-flow-delete-requests'
  region: us-west-2
backends:
  - id: 4a6c17c4-977a-4e69-b5e1-c12cde6f9253
    type: s3
    bucketName: k8s-tams-test
    region: us-west-2
    default: true
logs:
  level: info
server:
  port: 3000
