apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tams.trackit.io
spec:
  group: trackit.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                backend:
                  type: object
                  properties:
                    s3:
                      type: object
                      properties:
                        region:
                          type: string
                        bucket:
                          type: string
                      required:
                        - bucket
                  required:
                    - s3
                logs:
                  type: object
                  properties:
                    level:
                      type: string
                server:
                  type: object
                  properties:
                    port:
                      type: number
              required:
                - backend
          required:
            - spec
  scope: Namespaced
  names:
    plural: tams
    singular: tams
    kind: TAMS
    shortNames:
      - tams