apiVersion: tams.trackit.io/v1alpha1
kind: Store
metadata:
  name: example-store
spec:
  database:
    type: dynamodb
    flowTableName: 'k8s-tams-test'
    serviceTableName: 'k8s-tams-test-service'
  replicas: 1
  logs:
    level: info