apiVersion: tams.trackit.io/v1alpha1
kind: Store
metadata:
  name: example-store
spec:
  database:
    type: dynamodb
    region: us-west-2
    flowTableName: 'k8s-tams-test'
    serviceTableName: 'k8s-tams-test-service'
    mediaObjectTableName: 'k8s-tams-test-media-object'
  backends:
    - id: 4a6c17c4-977a-4e69-b5e1-c12cde6f9253
      type: s3
      default: true
      bucketName: k8s-tams-test
      region: us-west-2
  replicas: 1
  secretName: tams-aws-secret
  logs:
    level: info
