name: Check quick deploy file
on:
  pull_request:
  merge_group:

jobs:
  check-quickdeploy:
    runs-on: ubuntu-latest
    name: Check quickdeploy file
    steps:
      - uses: actions/checkout@v2
      - name: Check quickdeploy file
        run: |
          controller_content=$(cat ./k8s-controller/artifacts/tams/controller.yaml)
          crd_content=$(cat ./k8s-controller/artifacts/tams/crd.yaml)
          
          quick_deploy_content=$(cat ./k8s-controller/artifacts/tams/quick-deploy.yaml)
          
          expected_content=$(echo -e "$controller_content\n---\n$crd_content")
          
          echo "Comparing quickdeploy file content with expected content"
          diff <(echo -e "$quick_deploy_content") <(echo -e "$expected_content")
