name: Unit test
on:
  push:

jobs:
  run_test:
    name: Run service unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ./service
        run: npm install
      - name: Run unit test
        working-directory: ./service
        run: npm run test
