name: Unit test
on:
  push:

jobs:
  run_test:
    name: Run service unit test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup workdir
        run: cd ./service
      - name: Install dependencies
        run: npm install
      - name: Run unit test
        run: npm run test
