name: Verify Codegen
on:
  pull_request:
jobs:
  verify-codegen:
    runs-on: ubuntu-latest
    name: Verify Codegen
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          cd ./k8s-controller
          go mod vendor
      - name: Verify Codegen
        run: ./k8s-controller/hack/verify-codegen.sh
