name: Docker Image CI

on:
  push:
    branches: [ "master", "feat/cicd" ]
  pull_request:
    branches: [ "master", "feat/cicd" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the service Docker image
        run: docker build . --file ./service/Dockerfile --tag ghcr.io/trackit/tams-service:latest
      - name: Push the service Docker image
        run: docker push ghcr.io/trackit/tams-service:latest
